photobooth/booth/urls.py
from django.urls import path
from booth import views

from django.conf import settings
from django.conf.urls.static import static
from .views import  AppointmentTemplateView, ManageAppointmentTemplateView


urlpatterns = [
     path('', views.home, name='home'),
     path('portfolio/', views.portfolio, name='portfolio'),
     path('printing_page/', views.printing_page, name='printing_page'),
     path('branding_page/', views.branding_page, name='branding_page'),
     path('all_services/', views.all_services, name='all_services'),
     path('template_page/', views.template_page, name='template_page'),

     path('dashboard/', views.dashboard, name='dashboard'),
     path('about/', views.about, name='about'), 
     path('services/', views.services, name='services'),
     path("make-an-appointment/", AppointmentTemplateView.as_view(), name="appointment"),
     path('success_message/', views.success_message, name='success_message'),
     path("manage-appointments/", ManageAppointmentTemplateView.as_view(), name="manage"),

]
 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

photobooth/photobooth/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('booth.urls')),
    path('',include('users.urls')),


]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

photobooth/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    path('gallery', views.gallery, name='gallery'),
    path('photo/<str:pk>/', views.viewPhoto, name='photo'),
    path('delete_photo/<int:photo_id>/', views.deletePhoto, name='delete_photo'),
    path('add/', views.addPhoto, name='add'),
    path('view_home/', views.view_home, name='view_home'),     
    path('register/', views.register, name='register'),
    path('login/', views.custom_login, name='login'),
    path('profile/<int:pk>', views.profile, name='profile'),
    path('logout/', views.custom_logout, name='logout'),
    path('password-reset/', 
        PasswordResetView.as_view(
            template_name='users/account/password_reset.html',
            html_email_template_name='users/account/password_reset_email.html'
        ),
        name='password-reset'
    ),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/account/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/account/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='users/account/password_reset_complete.html'),name='password_reset_complete'),

    # path("register", views.register, name="register"),
    # path('login', views.custom_login, name='login'),
    # path('logout', views.custom_logout, name='logout'),
    # path('login', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # path('logout', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photobooth/booth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.


class Appointment(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    request = models.TextField(blank=True)
    sent_date = models.DateField(auto_now_add=True)
    select_date = models.DateField()
    accepted = models.BooleanField(default=False)
    accepted_date = models.DateField(auto_now_add=False, null=True, blank=True)

    def __str__(self):
        return self.first_name
    
    class Meta:
        ordering = ["-sent_date"]

photobooth/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.template.defaultfilters import slugify
import os

# Create your models here.
class CustomUser(AbstractUser):

    def image_upload_to(self, instance=None):
        if instance:
            return os.path.join("Users", self.username, instance)
        return None

    STATUS = (
        ('regular', 'regular'),
        ('subscriber', 'subscriber'),
        ('moderator', 'moderator'),
    )

    email = models.EmailField(unique=True)
    status = models.CharField(max_length=100, choices=STATUS, default='regular')
    description = models.TextField("Description", max_length=600, default='', blank=True)
    image = models.ImageField(default='images/user.jpg', upload_to="images/")
    phone_number=models.IntegerField(null=True, blank=True)
    address=models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.username
    
class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.name


class Photo(models.Model):
    class Meta:
        verbose_name = 'Photo'
        verbose_name_plural = 'Photos'
    
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(null=False, blank=False)
    description = models.TextField()

    def __str__(self):
        return self.description

photobooth/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(help_text='A valid email address, please.', required=True)

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()

        return user

class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username or Email'}),
        label="Username or Email*")

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))
    
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'image','email', 'description','phone_number','address']

photobooth/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import UserRegistrationForm, UserLoginForm,UserUpdateForm
from .decorators import user_not_authenticated

from .models import*



app_name='users'

# Create your views here.
# def index(request):
#     return render(request, 'index.html')


@login_required(login_url='login')
def gallery(request):
    user = request.user
    category = request.GET.get('category')
    if category == None:
        photos = Photo.objects.filter(category__user=user)
    else:
        photos = Photo.objects.filter(
            category__name=category, category__user=user)

    categories = Category.objects.filter(user=user)
    context = {'categories': categories, 'photos': photos}
    return render(request, 'booth/gallery.html', context)


# @login_required(login_url='login')
def viewPhoto(request, pk):
    photo = Photo.objects.get(id=pk)
    return render(request, 'booth/photo.html', {'photo': photo})

def view_home(request):
    photos=Photo.objects.all()[:16]
    context={
        'photos':photos
    }

    return render(request,'booth/view_home.html', context)


@login_required(login_url='login')
def addPhoto(request):
    user = request.user

    categories = user.category_set.all()

    if request.method == 'POST':
        data = request.POST
        images = request.FILES.getlist('images')

        if data['category'] != 'none':
            category = Category.objects.get(id=data['category'])
        elif data['category_new'] != '':
            category, created = Category.objects.get_or_create(
                user=user,
                name=data['category_new'])
        else:
            category = None

        for image in images:
            photo = Photo.objects.create(
                category=category,
                description=data['description'],
                image=image,
            )

        return redirect('gallery')

    context = {'categories': categories}
    return render(request, 'booth/add.html', context)


@login_required(login_url='login')
def deletePhoto(request, photo_id):
    user = request.user
    photo = get_object_or_404(Photo, id=photo_id)

    # Ensure the user trying to delete the photo is the owner
    if photo.category.user != user:
        return redirect('gallery')  # or handle unauthorized deletion differently

    if request.method == 'POST':
        # Call the delete method on the Photo model
        photo.delete()
        return redirect('gallery')

    return render(request, 'booth/delete_photo.html', {'photo': photo})



# @user_not_authenticated
def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, f"New account created: {user.username}")
            return redirect('login')

        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    else:
        form = UserRegistrationForm()

    return render(request=request,template_name="users/register.html",context={"form": form})

@login_required
def custom_logout(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("/")

# @user_not_authenticated
def custom_login(request):
    if request.method == "POST":
        form = UserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )
            if user is not None:
                login(request, user)
                # messages.success(request, f"Hello {user.username} You have been logged in")
                return redirect("gallery")

        else:
            for error in list(form.errors.values()):
                messages.error(request, error) 

    form = UserLoginForm()

    return render(request=request,template_name="users/login.html",context={"form": form})



def profile(request, pk):
    if request.method == "POST":
        user = request.user
        form = UserUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            user_form = form.save()
            messages.success(request, f'Your profile has been updated!')
            # Check if the user is redirected correctly
            print(f"Redirecting to profile for user {user_form.pk}")
            return redirect("profile", user_form.pk)
        else:
            # Print form errors for debugging
            for error in list(form.errors.values()):
                print(error)
            messages.error(request, "There was an error updating your profile.")

    user = get_user_model().objects.filter(pk=pk).first()
    if user:
        form = UserUpdateForm(instance=user)
        form.fields['description'].widget.attrs = {'rows': 1}
        return render(
            request=request,
            template_name="profile.html",
            context={"form": form}
        )
    
    return redirect("/")

photobooth/users/templates/users/login.html
{% extends 'booth/base.html' %}
{% load static %}

{% block content %}

{% include 'booth/header.html' %}



<!-- Section: Design Block -->



<section class="text-center text-lg-start">
    <style>
      .cascading-right {
        margin-right: -50px;
      }
  
      @media (max-width: 991.98px) {
        .cascading-right {
          margin-right: 0;
        }
      }
    </style>
  
    <!-- Jumbotron -->
    <div class="container py-4">
      <div class="row g-0 align-items-center">
        <div class="col-lg-6 mb-5 mb-lg-0">
          <div class="card cascading-right" style="
              background: hsla(0, 0%, 100%, 0.55);
              backdrop-filter: blur(30px);
              ">
                     <!-- Display errors if any -->
                {% if messages %}
                <div class="alert alert-danger">
                  <ul class="mb-0">
                    {% for message in messages %}
                      <li>{{ message }}</li>
                    {% endfor %}
                  </ul>
                </div>
              {% endif %}
            <div class="card-body p-5 shadow-5 text-center">
              <h2 class="fw-bold mb-5">Sign up now</h2>
              <form method='post' >
                {% csrf_token %}
                <!-- 2 column grid layout with text inputs for the first and last names -->
                <div class="row">
                  <div class="col-md-12 mb-4">
                    <div class="form-outline">
                      <input type="text" id="username" name="username"  class="form-control" />
                      <label class="form-label" for="form3Example1">Username</label>
                    </div>
                  </div>
                </div>
  
              

                <div class="form-outline mb-4">
                    <input type="password" name="password" id="form3Example4" class="form-control" />
                    <label class="form-label" for="form3Example4">Password</label>
                  </div>
  
             
  
                <!-- Submit button -->
                <button type="submit" class="btn btn-primary btn-block mb-4">
                  Sign in
                </button>
  
                
              </form>


                <!-- Register buttons -->
                <div class="text-center">
                  <p>You dont have an account?:</p>
                  <button type="button" class="btn btn-link btn-floating mx-1">
                   
                   <a href="{% url 'register' %}"> Sign Up</a>
                  </button>
   
                  <!-- <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-google"></i>
                  </button>
  
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-twitter"></i>
                  </button>
  
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-github"></i>
                  </button> -->
                </div>
            </div>
          </div>
        </div>
  
        <div class="col-lg-6 mb-5 mb-lg-0">
          <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" class="w-100 rounded-4 shadow-4"
            alt="" />
        </div>
      </div>
    </div>


    <!-- Jumbotron -->
  </section>
  <!-- Section: Design Block -->

  {% include 'booth/footer.html' %}
  <!-- ======= Footer ======= -->
 <!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

{% endblock %}

photobooth/users/templates/users/logout.html
{% extends "main/header.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3"  style="min-height:65vh;">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

photobooth/users/templates/users/register.html
{% extends 'booth/base.html' %}
{% load static %}

{% block content %}

{% include 'booth/header.html' %}



<!-- Section: Design Block -->



<section class="text-center text-lg-start">
    <style>
      .cascading-right {
        margin-right: -50px;
      }
  
      @media (max-width: 991.98px) {
        .cascading-right {
          margin-right: 0;
        }
      }
    </style>
  
    <!-- Jumbotron -->
    <div class="container py-4">
      <div class="row g-0 align-items-center">
        <div class="col-lg-6 mb-5 mb-lg-0">
          <div class="card cascading-right" style="
              background: hsla(0, 0%, 100%, 0.55);
              backdrop-filter: blur(30px);
              ">
                     <!-- Display errors if any -->
                {% if messages %}
                <div class="alert alert-danger">
                  <ul class="mb-0">
                    {% for message in messages %}
                      <li>{{ message }}</li>
                    {% endfor %}
                  </ul>
                </div>
              {% endif %}
            <div class="card-body p-5 shadow-5 text-center">
              <h2 class="fw-bold mb-5">Sign up now</h2>
              <form method='post' >
                {% csrf_token %}
                <!-- 2 column grid layout with text inputs for the first and last names -->
                <div class="row">
                  <div class="col-md-6 mb-4">
                    <div class="form-outline">
                      <input type="text" id="id_first_name" name="first_name"  class="form-control" />
                      <label class="form-label" for="form3Example1">Fisrt Name</label>
                    </div>
                  </div>

                  <div class="col-md-6 mb-4">
                    <div class="form-outline">
                      <input type="text" id="id_last_name" name="last_name"  class="form-control" />
                      <label class="form-label" for="form3Example1">Last Name</label>
                    </div>
                  </div>

                  <div class="col-md-6 mb-4">
                    <div class="form-outline">
                      <input type="text" id="id_username" name="username"  class="form-control" />
                      <label class="form-label" for="form3Example1">Username</label>
                    </div>
                  </div>

                  <div class="col-md-6 mb-4">
                    <div class="form-outline">
                      <input type="email" id="id_email" name="email"  class="form-control" />
                      <label class="form-label" for="form3Example1">Email</label>
                    </div>
                  </div>


                  <div class="col-md-6 mb-4">
                    <div class="form-outline">
                      <input type="password" id="id_password1" name="password1"  class="form-control" />
                      <label class="form-label" for="form3Example1">Password</label>
                    </div>
                  </div>

                  <div class="col-md-6 mb-4">

                  <div class="form-outline mb-4">
                    <input type="password" name="password2" id="id_password2" class="form-control" />
                    <label class="form-label" for="form3Example4">Confirm Password</label>
                  </div>
                  </div>
                </div>
  
              

                
  
             
  
                <!-- Submit button -->
                <button type="submit" class="btn btn-primary btn-block mb-4">
                  Sign in
                </button>
  
                
              </form>


                <!-- Register buttons -->
                <div class="text-center">
                  <p>You dont have an account?:</p>
                  <button type="button" class="btn btn-link btn-floating mx-1">
                   
                   <a href="{% url 'register' %}"> Sign Up</a>
                  </button>
   
                  <!-- <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-google"></i>
                  </button>
  
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-twitter"></i>
                  </button>
  
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-github"></i>
                  </button> -->
                </div>
            </div>
          </div>
        </div>
  
        <div class="col-lg-6 mb-5 mb-lg-0">
          <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" class="w-100 rounded-4 shadow-4"
            alt="" />
        </div>
      </div>
    </div>


    <!-- Jumbotron -->
  </section>
  <!-- Section: Design Block -->

  {% include 'booth/footer.html' %}
  <!-- ======= Footer ======= -->
 <!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

{% endblock %}