photobooth/booth/urls.py
from django.urls import path
from booth import views

from django.conf import settings
from django.conf.urls.static import static
from .views import  AppointmentTemplateView, ManageAppointmentTemplateView


urlpatterns = [
     path('', views.home, name='home'),
     path('portfolio/', views.portfolio, name='portfolio'),
     path('printing_page/', views.printing_page, name='printing_page'),
     path('branding_page/', views.branding_page, name='branding_page'),
     path('all_services/', views.all_services, name='all_services'),
     path('template_page/', views.template_page, name='template_page'),

     path('dashboard/', views.dashboard, name='dashboard'),
     path('about/', views.about, name='about'), 
     path('services/', views.services, name='services'),
     path("make-an-appointment/", AppointmentTemplateView.as_view(), name="appointment"),
     path('success_message/', views.success_message, name='success_message'),
     path("manage-appointments/", ManageAppointmentTemplateView.as_view(), name="manage"),

]
 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

photobooth/photobooth/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('booth.urls')),
    path('',include('users.urls')),


]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

photobooth/booth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.


class Appointment(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    request = models.TextField(blank=True)
    sent_date = models.DateField(auto_now_add=True)
    select_date = models.DateField()
    accepted = models.BooleanField(default=False)
    accepted_date = models.DateField(auto_now_add=False, null=True, blank=True)

    def __str__(self):
        return self.first_name
    
    class Meta:
        ordering = ["-sent_date"]

photobooth/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.template.defaultfilters import slugify
import os

# Create your models here.
class CustomUser(AbstractUser):

    def image_upload_to(self, instance=None):
        if instance:
            return os.path.join("Users", self.username, instance)
        return None

    STATUS = (
        ('regular', 'regular'),
        ('subscriber', 'subscriber'),
        ('moderator', 'moderator'),
    )

    email = models.EmailField(unique=True)
    status = models.CharField(max_length=100, choices=STATUS, default='regular')
    description = models.TextField("Description", max_length=600, default='', blank=True)
    image = models.ImageField(default='images/user.jpg', upload_to="images/")
    phone_number=models.IntegerField(null=True, blank=True)
    address=models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.username
    
class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.name


class Photo(models.Model):
    class Meta:
        verbose_name = 'Photo'
        verbose_name_plural = 'Photos'
    
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(null=False, blank=False)
    description = models.TextField()

    def __str__(self):
        return self.description

photobooth/booth/forms.py
from django import forms

photobooth/booth/views.py
from django.shortcuts import render, redirect, get_object_or_404
from users.models import *
from.forms import*
from django.core.mail import send_mail
from django.conf import settings
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.base import TemplateView
from django.core.mail import EmailMessage, message
from django.contrib import messages
from .models import *
from django.views.generic import ListView
import datetime
from django.template import Context
from django.template.loader import render_to_string, get_template



def home(request):
    if request.method == "POST":
        name = request.POST.get("name")
        email_address = request.POST.get("email")
        message = request.POST.get("message")

        email = EmailMessage(
            subject=f"{name} from Photobooth.",
            body=message,
            from_email=settings.EMAIL_HOST_USER,
            to=[settings.EMAIL_HOST_USER],
            reply_to=[email_address]
        )
        email.send()

        # Add a print statement for debugging
        print("Email sent successfully!")

        return redirect('success_message')
    else:
        return render(request, "booth/home.html")


class AppointmentTemplateView(TemplateView):
    template_name = "booth/appointment.html"

    def post(self, request):
        fname = request.POST.get("fname")
        lname = request.POST.get("fname")
        email = request.POST.get("email")
        select_date = request.POST.get("select_date")
        mobile = request.POST.get("mobile")
        message = request.POST.get("request")

        appointment = Appointment.objects.create(
            first_name=fname,
            last_name=lname,
            email=email,
            phone=mobile,
            select_date=select_date,
            request=message,
        )

        appointment.save()

        messages.add_message(request, messages.SUCCESS, f"Thanks {fname} for making an appointment, we will email you ASAP!")
        return HttpResponseRedirect(request.path)

class ManageAppointmentTemplateView(ListView):
    template_name = "booth/manage-appointments.html"
    model = Appointment
    context_object_name = "appointments"
    login_required = True
    paginate_by = 12


    def post(self, request):
        date = request.POST.get("date")
        appointment_id = request.POST.get("appointment-id")
        appointment = Appointment.objects.get(id=appointment_id)
        appointment.accepted = True
        appointment.accepted_date = datetime.datetime.now()
        appointment.save()

        data = {
            "fname":appointment.first_name,
            "date":date,
        }

        message = get_template('booth/email.html').render(data)
        email = EmailMessage(
            "About your appointment",
            message,
            settings.EMAIL_HOST_USER,
            [appointment.email],
        )
        email.content_subtype = "html"
        email.send()

        messages.add_message(request, messages.SUCCESS, f"You accepted the appointment of {appointment.first_name}")
        return HttpResponseRedirect(request.path)


    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        appointments = Appointment.objects.all()
        context.update({   
            "title":"Manage Appointments"
        })
        return context
    


def dashboard(request):
    return render(request,'booth/dashboard.html')

def success_message(request):
    return render(request,'booth/success_message.html')


def printing_page(request):
    return render(request,'booth/printing_page.html')

def branding_page(request):
    return render(request,'booth/branding_page.html')

def all_services(request):
    return render(request,'booth/all_services.html')

def template_page(request):
    return render(request,'booth/template_page.html')



def portfolio(request):
    category = request.GET.get('category')
    
    if category is None:
        photos = Photo.objects.all()  
        # Fetch all photos without filtering by user
    else:
        photos = Photo.objects.filter(category__name=category)

    categories = Category.objects.all() 
     # Fetch all categories without filtering by user
    context = {'categories': categories, 'photos': photos}
    
    return render(request, 'booth/portfolio.html', context)





def about(request):
    return render(request,'booth/about.html')

def services(request):
    return render(request,'booth/services.html')

photobooth/templates/booth/about.html
{% extends 'booth/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'assets/photo/css/style.css' %}" type="text/css"> 

{% include 'booth/header.html' %}
<!-- <link rel="stylesheet" href="{% static 'assets/css/css/reset.css' %}" />-->
<!-- <link rel="stylesheet" href="{% static 'assets/css/css/style.css' %}" /> -->
<link rel="stylesheet" href="{% static 'assets/css/css/swiper.css' %}" /> 


 <!-- Css Styles -->

<!-- ======= About Section ======= -->
  <!-- ======= About Section ======= -->
  <section id="about" class="about">
    <div class="container">
      <div class="row">
        <section class="projects-section" id="projects">
          <div class="container px-4 px-lg-5">
              <!-- Project One Row-->
              <div class="row gx-0 mb-5 mb-lg-0 justify-content-center">
                  <div class="col-lg-6"><img class="img-fluid" src="{% static 'assets/images/webp/booth.jpg' %}" alt="..." /></div>
                  <div class="col-lg-6">
                      <div class="bg-light text-center h-100 project">
                          <div class="d-flex h-100">
                              <div class="project-text w-100 my-auto text-center text-lg-left">
                                  <h4 class="text-dark">Our Booth</h4>
                                  <p class="mb-0 text-dark-50"> TuneBox photo-booth is a new venture in the Kenyan market .This is our Portable Booth which offers perfect lighting, privacy and fun user experience , this experience delights guests and enhances your event or venue.</p>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <!-- Project Two Row-->
              <div class="row gx-0 justify-content-center">
                  <div class="col-lg-6"><img class="img-fluid" src="{% static 'assets/images/webp/softw.jpg' %}" alt="..."/></div>
                  <div class="col-lg-6 order-lg-first">
                      <div class="bg-light text-center h-100 project">
                          <div class="d-flex h-100">
                              <div class="project-text w-100 my-auto text-center text-lg-right">
                                  <h4 class="text-dark">Our Software </h4>
                                  <p class="mb-0 text-dark-50"> 
                                    
                                     Our photos are taken with a DSLR camera, instantly printed. The high-quality printed photos come in different sizes of 2*6, 4*6,5*7, 6*8 prints .
                                    We also provide personalized photobooth templates, that matches your event's theme perfectly .
                                    
                               </p>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </section>



      </div>

    </div>

</section>
 

  <section class="services spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="services__title">
                    <div class="section-title">
                        <span>Our services</span>
                        <h2>What We do?</h2>
                    </div>
                    <p>If you hire a videographer of our team you will get a video professional to make a custom
                        video for your business and, once the project is over.</p>
                    <a href="{% url 'all_services' %}" class="primary-btn">View all services</a>
                  

                </div>
            </div>
     
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        
                        <div class="services__item">
                            <div class="services__item__icon">           
                                    <img src="{% static 'assets/img/icons/si-1.png' %}" alt="">                         
                            </div>
                            <h4>Template Creation</h4> 
                            <p>Whether you’re halfway through the editing process, or you haven’t even started, our
                                post production services can put the finishing touches.</p>
                        </div>
                 
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="services__item">
                            <div class="services__item__icon">
                                <img src="{% static 'assets/img/icons/si-2.png' %}" alt="">
                            </div>
                            <h4>Printing</h4>
                            <p>Whether you’re halfway through the editing process, or you haven’t even started, our
                                post production services can put the finishing touches.</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="services__item">
                            <div class="services__item__icon">
                                <img src="{% static 'assets/img/icons/si-3.png' %}" alt="">
                            </div>
                            <h4>Video distribution</h4>
                            <p>Whether you’re halfway through the editing process, or you haven’t even started, our
                                post production services can put the finishing touches.</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="services__item">
                            <div class="services__item__icon">
                                <img src="{% static 'assets/img/icons/si-4.png' %}" alt="">
                            </div>
                            <h4>Video hosting</h4>
                            <p>Whether you’re halfway through the editing process, or you haven’t even started, our
                                post production services can put the finishing touches.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
  
      
         <!-- ======= Counts Section ======= -->
        <section id="counts" class="counts  section-bg">
          <div class="container_fluid">

            <div class="row no-gutters">

              <div class="col-3"></div>

              <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch">
                <div class="count-box">
                  <i class="bi bi-emoji-smile"></i>
                  <span data-purecounter-start="0" data-purecounter-end="232" data-purecounter-duration="1" class="purecounter"></span>
                  <p><strong>Happy Clients</strong> </p>
                
                </div>
              </div>
              <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch">
                <div class="count-box">
                  <i class="bi bi-journal-richtext"></i>
                  <span data-purecounter-start="0" data-purecounter-end="521" data-purecounter-duration="1" class="purecounter"></span>
                  <p><strong>Projects</strong> </p>
                </div>
              </div>
            </div>

        </div>

    
        </div>

      </div>
      </section><!-- End Services Section -->
         <!-- Js Plugins -->
    <script src="{% static 'assets/photo/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/photo/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/photo/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/photo/js/mixitup.min.js' %}"></script>
    <script src="{% static 'assets/photo/js/masonry.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/photo/js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'assets/photo/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/photo/js/main.js' %}"></script>



{% include 'booth/footer.html' %}
<!-- ======= Footer ======= -->
<!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
    class="bi bi-arrow-up-short"></i></a>

{% endblock %}

photobooth/templates/booth/all_services.html
{% extends 'booth/base.html' %}
{% load static %}

{% block content %}

  <!-- ======= Header ======= -->

  {% include 'booth/header.html' %}
<!-- End Header -->

  <!-- ======= Hero Section ======= -->  
    <link rel="stylesheet" href="{% static 'assets/css/css/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/css/swiper.css' %}" /> 
    <link rel="stylesheet" href="{% static 'assets/css/css/style_blog.css' %}">
    <link rel="stylesheet" href="{% static 'assets/photo/css/style.css' %}" type="text/css"> 



<br><br><br>

 <!-- Frame Section  -->
 <div class="frame">
	<div class="text">
		<span>❤</span>
		<span></span>
		<span>E</span>
		<span>V</span>
		<span>O</span>
		<span>L</span>
		<span></span>
		<span>H</span>
		<span>T</span>
		<span>I</span>
		<span>W</span>
		<span></span>
		<span>E</span>
		<span>D</span>
		<span>A</span>
		<span>M</span>
		<span></span>
		<span>❤</span>
		<span></span>
		<span>E</span>
		<span>V</span>
		<span>O</span>
		<span>L</span>
		<span></span>
		<span>H</span>
		<span>T</span>
		<span>I</span>
		<span>W</span>
		<span></span>
		<span>E</span>
		<span>D</span>
		<span>A</span>
		<span>M</span>
		<span></span>
		<span>❤</span>
		<span></span>
		<span>E</span>
		<span>V</span>
		<span>O</span>
		<span>L</span>
		<span></span>
		<span>H</span>
		<span>T</span>
		<span>I</span>
		<span>W</span>
		<span></span>
		<span>E</span>
		<span>D</span>
		<span>A</span>
		<span>M</span>

	</div>
</div>
</div>
 <!-- End Frame Section  -->

 <!-- Portfolio Section Begin -->

   
 <section class="portfolio spad">
  <div class="container">
      <div class="row">
          <div class="col-lg-12">
              <ul class="portfolio__filter">
                  <li class="active" data-filter="*">All</li>
                  <li data-filter=".branding">Branding</li>
                  <li data-filter=".digital-marketing">Digital marketing</li>
                  <li data-filter=".web">Templates</li>
                  <li data-filter=".photography">Photography</li>
                  <li data-filter=" .ecommerce">Framing</li>
              </ul>
          </div>
      </div>
      <div class="gallery-container">
                   
        <!-- Gallery -->
        <div class="galleries">
            <!-- Wedding Gallery -->
            <div class="gallery active" data-name="Branding">
                <div>
                    <a data-fslightbox="Templates" href="./assets/images/templet/1.png"
                    class="gallery-item">
                  <img src="{% static 'assets/images/templet/1.png' %}">
              </a>
                  
                  <a data-fslightbox="Branding" href="{% static 'assets/images/templet/1.png' %}"
                  class="gallery-item">
                  <img src="{% static 'assets/images/templet/1.png' %}"
                      alt="Wedding photobooth rental" />
              </a>
              
          <a data-fslightbox="wedding" href="{% static 'assets/images/templet/2.png' %}"
          class="gallery-item">
          <img src="{% static 'assets/images/templet/2.png' %}" alt="Wedding" />
          </a>
                 
              <a data-fslightbox="wedding" href="{% static 'assets/images/templet/3.png' %}" class="gallery-item">
                 <img src="{% static 'assets/images/templet/3.png' %}" alt="Wedding photobooth rental" />
              </a>

                    <a data-fslightbox="wedding" href="{% static 'assets/images/templet/4.png' %}"
                        class="gallery-item">
                        <img src="{% static 'assets/images/templet/4.png' %}"
                            alt="Wedding photobooth rental" />
                    </a>
                    <a data-fslightbox="wedding" href="{% static 'assets/images/templet/5.png' %}"
                    class="gallery-item">
                    <img src="{% static 'assets/images/templet/5.png' %}" alt="Wedding" />
                </a>
                    <a data-fslightbox="wedding" href="{% static 'assets/images/templet/6.png' %}"
                        class="gallery-item">
                        <img src="{% static 'assets/images/templet/6.png' %}" alt="Wedding" />
                    </a>
                    <a data-fslightbox="wedding" href="{% static 'assets/images/templet/templ.jpg' %}"
                    class="gallery-item">
                    <img src="{% static 'assets/images/templet/templ.jpg' %}" alt="Wedding" />
                </a>
                   
                </div>
                <a href="{% url 'view_home' %}" target="_blank" class="btn1">View
                    More</a>
            </div>
            
                                </div>
                                <!-- Gallery  End -->
                          
            
</div>
      </div>
      <div class="row">
          <div class="col-lg-12">
              <div class="pagination__option">
                  <a href="#" class="arrow__pagination left__arrow"><span class="arrow_left"></span> Prev</a>
                  <a href="#" class="number__pagination">1</a>
                  <a href="#" class="number__pagination">2</a>
                  <a href="#" class="arrow__pagination right__arrow">Next <span class="arrow_right"></span></a>
              </div>
          </div>
      </div>
  </div>
</section>
<!-- Portfolio Section End -->



<script src="{% static 'assets/photo/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'assets/photo/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/photo/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'assets/photo/js/mixitup.min.js' %}"></script>
<script src="{% static 'assets/photo/js/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'assets/photo/js/jquery.slicknav.js' %}"></script>
<script src="{% static 'assets/photo/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'assets/photo/js/main.js' %}"></script>

</main><!-- End #main -->
{% include 'booth/chatbox.html' %}

{% include 'booth/footer.html' %}
<!-- ======= Footer ======= -->
<!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

{% endblock %}

photobooth/templates/booth/chatbox.html
<script
    src='../../static/assets/js/whatsapp.js'
    async
    onLoad="whatsappButton({
    buttonName:'Message Us',
    buttonIconSize: '22',
    brandImageUrl:'../../static/assets/images/logo1.png',
    buttonMargin:'true',
    brandName:'tunebox',
    brandSubtitleText:'Typically replies within a day',
    buttonSize:'regular',
    buttonPosition:'right',
    callToAction:'Start Chat',
    phoneNumber:'254704099049',
    welcomeMessage:'Hi there 👋',
    prefillMessage:'Hi, I want to know more!',
    })"
    >
</script>

photobooth/templates/booth/contact.html
    <div class="row">

        <!-- <div class="col-lg-6 ">
          <iframe class="mb-4 mb-lg-0" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621" frameborder="0" style="border:0; width: 100%; height: 384px;" allowfullscreen></iframe>
        </div> -->

        <div class="col-lg-12">
       
            <form action="{% url 'home' %}" method="post" role="form" class="php-email-form">
                {% csrf_token %}
                <div class="row">
              <div class="col-md-6 form-group">
                <input type="text" name="name" class="form-control" id="id_name" placeholder="Your Name" required>
                <div class="error" id="err-name" style="display: none;">Please enter name</div>

              </div>
              <div class="col-md-6 form-group mt-3 mt-md-0">
                <input type="email" class="form-control" name="email" id="id_email" placeholder="Your Email" required>
                <div class="error" id="err-emailvld" style="display: none;">E-mail is not a valid format</div> 

              </div>
            </div>
        
            <div class="form-group mt-3">
              <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
              <div class="error" id="err-message" style="display: none;">Please enter message</div>

            </div>
            <div class="my-3">
              <div class="loading">Loading</div>
              <div class="error-message"></div>
              <div class="sent-message">Your message has been sent. Thank you!</div>
            </div>
            <div class="text-center"><button type="submit" class="rounded-pill btn-dark">Send Message</button></div>
          </form>

    
        </div>

      </div>  

photobooth/templates/booth/delete_appointment.html
{% extends 'booth/base.html' %}
{% load static %}

{% block content %}

{% include 'booth/header.html' %}


<!-- your_template_for_delete_confirmation.html -->
<br><br><br><br>

          <div class="modal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Modal title</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <p>Modal body text goes here.</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary">Save changes</button>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>

          </div>
          
             <div class="container">
               
                  <form action="{% url 'delete_appointment' appointment.id %}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-danger">Confirm Delete</button>
                      <a href="{% url 'manage-appointments' %}" class="btn btn-secondary">Cancel</a>
                  </form>
           
             </div>
         


{% include 'booth/footer.html' %}
<!-- ======= Footer ======= -->
<!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

{% endblock %}

photobooth/templates/booth/delete_photo.html
{% extends 'booth/base.html' %}
{% load static %}

{% block content %}

{% include 'booth/header.html' %}


<!-- your_template_for_delete_confirmation.html -->
<br><br><br><br>

          <div class="modal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Modal title</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <p>Modal body text goes here.</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary">Save changes</button>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>

          </div>
          
             <div class="container">
                <form method="post" action="{% url 'delete_photo' photo.id %}">
                  {% csrf_token %}
                  <div class="modal-dialog" role="document">
                      <div class="modal-content">
                          <div class="modal-header">
                              <h5 class="modal-title">Delete Photo</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                              </button>
                          </div>
                          <div class="modal-body">
                              <p>Are you sure you want to delete the photo?</p>
                          </div>
                          <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                              <button type="submit" class="btn btn-primary">Delete</button>
                          </div>
                      </div>
                  </div>
                </form>
             </div>
         


{% include 'booth/footer.html' %}
<!-- ======= Footer ======= -->
<!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

{% endblock %}

photobooth/templates/booth/photo.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Photo</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

</head>

<body class="m-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col">

                <a href="{% url 'portfolio' %}" class="btn btn-dark my-3">Go Back</a>

                <div style="height: 90vh;">
                    <img style="max-width: 100%; max-height: 100%;" src="{{photo.image.url}}">

                    <p>{{photo.description}}</p>
                </div>

            </div>
        </div>
    </div>

</body>

</html>